name: Swift

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Checking out our code base
    - uses: actions/checkout@v2
    
    - name: Force Xcode 13
      run: sudo xcode-select -switch /Applications/Xcode.app

    #- name: Build
      #run: swift build -v

   # - name: Run tests
     # run: swift test -v
      
